# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bf5472c84b033938e4f3cf3e9abd7eaa"
name = "Upcart AlpMi"
application_url = "https://upcart.tisortgetir.com"
embedded = true

[access_scopes]
scopes = "read_discounts,read_locales,read_orders,read_products,read_themes,write_discounts,write_files,write_products,write_translations"

[auth]
redirect_urls = [
  "https://upcart.tisortgetir.com/auth/callback",
  "https://upcart.tisortgetir.com/auth/shopify/callback",
  "https://upcart.tisortgetir.com/api/auth/callback"
]

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

[app_proxy]
url = "https://upcart.tisortgetir.com/api/proxy"
subpath = "upcard"
prefix = "apps"

[shop.metafields.app.live_cart_config]
type = "json"
name = "Upcart AlpMi Canlı Sepet"
description = "Yayınlanmış Upcart AlpMi sepet çekmecesi yapılandırması"
access.admin = "merchant_read_write"
access.storefront = "public_read"

[build]
automatically_update_urls_on_dev = true
